### ISSUE TITLE
Version Issue for v2.5

### ISSUE THREAD

**Issue by tncxrb** [stylemessiah/GPay-SQLite-Fix#18]
After installing and rebooting v2.5, it shows up under magisk module list as v2.4. I have tried upgrading from 2.4>2.5, I have tried a clean install, removing v2.4 then installing v2.5. No matter what it still shows up under module list. Just wanted to see if its some kind of bug, If anyone else has seen this behavior, and any general info. Stuff like this drives me insane, when I cant figure out what/why something is happening. Any feedback/info is greatly appreciated. Thanks to devs/maintainers for your work on this project, I have used it basically since day 1 of it being available, you guys rock keep up the good work and thank you. Let me know if you need any kind of special debug info. Just tell me how/what you need me to pull. Happy Holidays everyone!

**Comment by stylemessiah** [comment]
sorry for the delay in replying to this, for some reason i never get the github notifications

the issue is almost certainly my stupidity and inability to remember to update the version tag inside the module.prop file. this should have been corrected by now......

also this is only made by one idiot with little spare time....should explain the half assed feel of things :)
